version: '3.8'

services:
  web:
    build:
      context: ./library-web
    container_name: library_web
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  bot:
    build:
      context: ./library-bot
    container_name: telegram_bot
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: aifu_library
      POSTGRES_USER: aifu_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: aifu_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
