version: '3.8'

services:
  web:
    build:
      context: ./library-web
    container_name: library_web
    environment:
      - BOT_HOST=http://library-bot
      - BOT_PORT=8081
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  bot:
    build:
      context: ./library-bot
    container_name: telegram_bot
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_management &&
               rabbitmq-plugins enable --offline rabbitmq_stomp &&
               rabbitmq-server"


volumes:
  pgdata:
