spring:
  application:
    name:
      library-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    password: root123
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: message
    encoding: UTF-8
bot:
  token:
    7284272709:AAHVHFQTs6fG7ijdzg6cHwZI9MnjUSlJ9PU
  name:
    AIFU Library


springdoc:
  api-docs:
    path: /v1-api
  swagger-ui:
    path: /swagger-ui.html

internal:
  token:
    94e637a1ff9a4c8e87de5198d78a5bc2c3067d76b9d2417ea54721370b7fd52e

server:
  port: 8081