spring:
  application:
    name:
      library-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    password: root123
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
bot:
  token:
    7284272709:AAHVHFQTs6fG7ijdzg6cHwZI9MnjUSlJ9PU
  name:
    AIFU Library
