spring:
  application:
    name:
     library-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    password: root123
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  messages:
    basename: message
    encoding: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true
bot:
  token:
    7284272709:AAHVHFQTs6fG7ijdzg6cHwZI9MnjUSlJ9PU
  name:
    AIFU Library

server:
  port: 8081
security:
  hashing:
    passport-salt: "a1b2c3!@#YourVerySecretKeyShouldBeHere#@!c3b2a1"  #"a1b2c3!@#X9fT7kL2qP0sZ8rD$Mh6&Vr4#@!c3b2a1"