spring:
  application:
    name: migration-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    username: postgres
    password: root123
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
