spring:
  config:
    import: application-private.yaml
  application:
    name: library-web
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

---

cloudinary:
  cloud_name: dfirqlklp
  api_key: 575239947937242
  api_secret: Cc5VKNT6F6RALyThRISMmFN45hA
