spring:
  application:
    name: library-web
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: application-private.yaml
file:
  upload-dir: E:/files/
