spring:
  config:
    import: application-private.yaml
  application:
    name: library-web
  datasource:
    url: jdbc:postgresql://localhost:5432/aifu_library
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

---

cloudinary:
  cloud_name: dfirqlklp
  api_key: 575239947937242
  api_secret: Cc5VKNT6F6RALyThRISMmFN45hA


importer:
  column-aliases:
    passportCode: passportcard, passport, pasport, паспорт, passport code
    surname: surname, last name, familiya, фамилия
    name: name, first name, ism, имя
    degree: degree, darajasi, степень
    faculty: faculty, fakultet, факультет
    cardNumber: card rifd, rfid, cardnumber, card number, karta raqami