internal:
  token:
    94e637a1ff9a4c8e87de5198d78a5bc2c3067d76b9d2417ea54721370b7fd52e

statistics:
  baseUri:
    http://localhost:8081/api/statistics

action:
  borrow:
    http://localhost:8081/action/book/borrow
  return:
    http://localhost:8081/action/book/return
  extend:
    http://localhost:8081/action/book/extend
  registration:
    http://localhost:8081/action/registration

notification:
  unread:
    http://localhost:8081/notification/unread
  getAll:
    http://localhost:8081/notification
  get:
    http://localhost:8081/notification

user:
  BaseUri:
    http://localhost:8081/api/user
