internal:
  token:
    94e637a1ff9a4c8e87de5198d78a5bc2c3067d76b9d2417ea54721370b7fd52e

aifu:
  external:
    host: ${BOT_HOST:http://localhost}
    port: ${BOT_PORT:8081}
    base-url: ${aifu.external.host}:${aifu.external.port}

statistics:
  baseUri: ${aifu.external.base-url}/api/statistics

booking:
  baseUri: ${aifu.external.base-url}/api/admin/booking

action:
  borrow: ${aifu.external.base-url}/action/book/borrow
  return: ${aifu.external.base-url}/action/book/return
  extend: ${aifu.external.base-url}/action/book/extend
  registration: ${aifu.external.base-url}/action/registration

notification:
  unread: ${aifu.external.base-url}/notification/unread
  getAll: ${aifu.external.base-url}/notification
  get: ${aifu.external.base-url}/notification
  type: ${aifu.external.base-url}/notification/type

user:
  baseUri: ${aifu.external.base-url}/api/user
