spring:
  config:
    import:
      application-private.yaml
  application:
    name: library-web
#  rabbitmq:
#    host: rabbitmq
#    port: 61613
#    username: guest
#    password: guest
  datasource:
#    url: jdbc:postgresql://localhost:5432/aifu_library
#    password: root123
    url: jdbc:postgresql://aifu-db.c3wi2qakgedd.eu-north-1.rds.amazonaws.com:5432/aifu_library
    password: root1234
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

file:
  upload-dir: E:/files
